# TravisCI configuration for Slic3r - https://slic3r.org
# 
# We build Linux and macOS versions on TravisCI, both the main program
# (perl/C++) and the pure C++ one.
# 
# Each job performs the following steps:
# - install dependencies (cached across builds)
# - build
# - test
# - package
# - deploy to dl.slic3r.org (except for the cppgui branch)

language: generic
dist: trusty

before_install:
    - sh package/common/travis-decrypt-key
    - export SLIC3R_GIT_VERSION=$(git rev-parse --short HEAD)

script:
    - if [[ "${TRAVIS_OS_NAME}" == "linux" && "$TARGET" == "main" ]]; then ./package/linux/travis-build-main.sh || travis_terminate 1; fi
    - if [[ "${TRAVIS_OS_NAME}" == "linux" && "$TARGET" == "cpp"  ]]; then ./package/linux/travis-build-cpp.sh || travis_terminate 1; fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx"   && "$TARGET" == "main" ]]; then ./package/osx/travis-build-main.sh || travis_terminate 1; fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx"   && "$TARGET" == "cpp"  ]]; then ./package/osx/travis-build-cpp.sh || travis_terminate 1; fi

branches:
  only:
  - master
  - cppgui
  - coverity-scan

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'deb http://download.opensuse.org/repositories/science:/dlr/xUbuntu_14.04/ /'
      key_url: 'https://download.opensuse.org/repositories/science:dlr/xUbuntu_14.04/Release.key'
    packages:
    - g++-7
    - gcc-7
    - g++-8
    - gcc-8
    - libgtk2.0-0 
    - libgtk2.0-dev
    - freeglut3
    - cmake
    - wx3.0-headers
    - libwxgtk3.0-dev
    - wx-common
  ssh_known_hosts: dl.slic3r.org

matrix:
    include:
        - os: linux
          env:
            - TARGET=main
          cache:
            directories:
              - $HOME/boost_1_63_0
              - $HOME/perl5
              - $HOME/wx302
              - local-lib
          after_success:
            - if [[ "${TRAVIS_BRANCH}" != "cppgui" ]]; then source ${HOME}/perl5/perlbrew/etc/bashrc; perlbrew switch slic3r-perl; ./package/linux/travis-deploy-main.sh || travis_terminate 1; fi

        - os: linux
          env: 
            - TARGET=cpp
            - CACHE=$HOME/cache
          cache:
            apt: true
            directories:
              - $HOME/cache
          after_success:
            - package/linux/travis-deploy-cpp.sh

        # While this works, it does not appear to be needed as the 10.13 builds
        # work on 10.12 as well.
        # - os: osx
        #   # osx_image: xcode8 # OS X 10.11
        #   osx_image: xcode9.2 # OS X 10.12
        #   env:
        #     - TARGET=main
        #   cache:
        #     directories:
        #       - /usr/local/Homebrew
        #       - $HOME/Library/Caches/Homebrew
        #       - local-lib

              # OSX errors out consistently for Perl now too. Back to jenkins.
              #        - os: osx
              #          osx_image: xcode9.4 # OS X 10.13
              #          env:
              #            - TARGET=main
              #          cache:
              #            directories:
              #              - /usr/local/Homebrew
              #              - $HOME/Library/Caches/Homebrew
              #              - local-lib
              #          after_success:
              #            - if [[ "${TRAVIS_BRANCH}" != "cppgui" ]]; then ./package/osx/travis-deploy-main.sh || travis_terminate 1; fi

        # OSX is erroring out consistently for C++, remove and debug
              #        - os: osx
              #          osx_image: xcode9.4
              #          env:
              #            - TARGET=cpp
              #            - CACHE=$HOME/cache
              #          cache:
              #            ccache: true
              #            directories:
              #              - /usr/local/Homebrew
              #              - $HOME/cache
              #              - $HOME/Library/Caches/Homebrew

env:
  global:
  - secure: eEVRZNMv7FM6jrOU9iAFkDhWxFQ1WtHBEaObImcvtFUxy6vWSt3ehFFeTRouj3uHQAnbvUzziDyvPPm8/95alv5g/du8ML6YzzqKBKfazM0xQ7SF6R2DQL8lfFIp+RSV7T02byEP1f1g7Zva7xH9szIlDcSfU0pXW4KWbkBFMd8=
  - secure: gj338h+qHGccTD/VQFmEJkqdg2McIe2pO0iZ4Ae9BvY5vxkIML4BpoYZQXQTqiAOETnUjlcknY9lx0hI/PfkDD9MSJc5BC/3fMYRCu3SgAclEwklWf9vvtodUeT69mtnZuw1zze1nTbExuOw2mepbqFjxKKMl+9l5oCz4O54fXU=

notifications:
  irc:
    channels:
    - chat.freenode.net#slic3r
    on_success: change
    on_failure: always
    use_notice: true
